### ISSUE TITLE
Trouble upgrading from 1.1.12 to 2.1.0

### ISSUE THREAD

**Issue by G3z** [bezhanSalleh/filament-shield#92]
When launching the `php artisan shield:upgrade` command I get an error related to migrations
I'm using postgres as database

```
$ php artisan shield:upgrade
shield upgraded.
***************************************************
*     Following operations will be performed:     *
***************************************************

-  Publishes core package config
-  Publishes core package migration
   - On fresh applications database will be migrated
   - You can also force this behavior by supplying the --fresh option
-  Creates a filament user
   - Assigns Super Admin role if enabled in config
   - And/Or Assigns Filament User role if enabled in config
-  Discovers filament resources and generates Permissions and Policies accordingly
   - Will override any existing policies if available

 Do you wish to continue? (yes/no) [yes]:
 > yes

   INFO  Publishing assets.  

  File [config/permission.php] already exists .............................................................................................. SKIPPED  
  File [database/migrations/2022_06_06_164730_create_permission_tables.php] already exists ................................................. SKIPPED  

Core Package config published.
   INFO  Publishing [filament-shield-config] assets.  

  Copying file [vendor/bezhansalleh/filament-shield/config/filament-shield.php] to [config/filament-shield.php] ............................... DONE

PDOException: SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop table permissions because other objects depend on it
DETAIL:  constraint model_has_permissions_permission_id_foreign on table model_has_permissions depends on table permissions
constraint role_has_permissions_permission_id_foreign on table role_has_permissions depends on table permissions
HINT:  Use DROP ... CASCADE to drop the dependent objects too. in /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:544
Stack trace:
#0 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(544): PDOStatement->execute()
#1 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\Database\Connection->Illuminate\Database\{closure}('DROP TABLE IF E...', Array)
#2 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('DROP TABLE IF E...', Array, Object(Closure))
#3 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->run('DROP TABLE IF E...', Array, Object(Closure))
#4 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\Database\Connection->statement('DROP TABLE IF E...')
#5 /code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Database\DatabaseManager->__call('statement', Array)
#6 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(110): Illuminate\Support\Facades\Facade::__callStatic('statement', Array)
#7 /code/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(264): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->BezhanSalleh\FilamentShield\Commands\{closure}('permissions', 0)
#8 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(110): Illuminate\Support\Collection->each(Object(Closure))
#9 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(53): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->install(true)
#10 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->handle()
#11 /code/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\Container\Container->call(Array)
#16 /code/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#17 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#18 /code/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(68): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#19 /code/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\Console\Command->runCommand('shield:install', Array, Object(Illuminate\Console\OutputStyle))
#20 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldUpgradeCommand.php(44): Illuminate\Console\Command->call('shield:install', Array)
#21 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BezhanSalleh\FilamentShield\Commands\MakeShieldUpgradeCommand->handle()
#22 /code/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\Container\Container->call(Array)
#27 /code/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /code/vendor/symfony/console/Application.php(998): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /code/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(BezhanSalleh\FilamentShield\Commands\MakeShieldUpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /code/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /code/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /code/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop table permissions because other objects depend on it
DETAIL:  constraint model_has_permissions_permission_id_foreign on table model_has_permissions depends on table permissions
constraint role_has_permissions_permission_id_foreign on table role_has_permissions depends on table permissions
HINT:  Use DROP ... CASCADE to drop the dependent objects too. (SQL: DROP TABLE IF EXISTS permissions) in /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
Stack trace:
#0 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(719): Illuminate\Database\Connection->runQueryCallback('DROP TABLE IF E...', Array, Object(Closure))
#1 /code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\Database\Connection->run('DROP TABLE IF E...', Array, Object(Closure))
#2 /code/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\Database\Connection->statement('DROP TABLE IF E...')
#3 /code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Database\DatabaseManager->__call('statement', Array)
#4 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(110): Illuminate\Support\Facades\Facade::__callStatic('statement', Array)
#5 /code/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(264): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->BezhanSalleh\FilamentShield\Commands\{closure}('permissions', 0)
#6 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(110): Illuminate\Support\Collection->each(Object(Closure))
#7 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldInstallCommand.php(53): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->install(true)
#8 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BezhanSalleh\FilamentShield\Commands\MakeShieldInstallCommand->handle()
#9 /code/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#11 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\Container\Container->call(Array)
#14 /code/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#15 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#16 /code/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(68): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#17 /code/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\Console\Command->runCommand('shield:install', Array, Object(Illuminate\Console\OutputStyle))
#18 /code/vendor/bezhansalleh/filament-shield/src/Commands/MakeShieldUpgradeCommand.php(44): Illuminate\Console\Command->call('shield:install', Array)
#19 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BezhanSalleh\FilamentShield\Commands\MakeShieldUpgradeCommand->handle()
#20 /code/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#22 /code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#23 /code/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#24 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\Container\Container->call(Array)
#25 /code/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 /code/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#27 /code/vendor/symfony/console/Application.php(998): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /code/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(BezhanSalleh\FilamentShield\Commands\MakeShieldUpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /code/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /code/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /code/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 {main}
Freshening up shield migrations.
   INFO  Running migrations.  

  2022_06_06_164730_create_permission_tables .............................................................................................. 7ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "permissions" already exists (SQL: create table "permissions" ("id" bigserial primary key not null, "name" varchar(255) not null, "guard_name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
    755▕         // If an exception occurs when attempting to run a query, we'll format the error
    756▕         // message to include the bindings with SQL, which will make this exception a
    757▕         // lot more helpful to the developer instead of just the database's errors.
    758▕         catch (Exception $e) {
  ➜ 759▕             throw new QueryException(
    760▕                 $query, $this->prepareBindings($bindings), $e
    761▕             );
    762▕         }
    763▕     }

      +9 vendor frames 
  10  database/migrations/2022_06_06_164730_create_permission_tables.php:35
      Illuminate\Support\Facades\Facade::__callStatic("create")

      +49 vendor frames 
  60  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by bezhanSalleh** [comment]
the easies way is to drop permission related tables from database and remove the `*_permissions_table` record from your migrations table...  backup your current config and update to the latest then 
`php artisan vendor:publish --tag=filament-shield-config --force `
set the config as per your backedup config and run `shield:install`
